# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Example-PagingAndSort
version:      v0.0.1
version_from: lib/Catalyst/Example/PagingAndSort.pm
installdirs:  site
requires:
    Catalyst:                      0
    Catalyst::View::TT:            0.2
    File::Spec:                    0
    HTML::Entities:                0
    Test::More:                    0
    URI::Escape:                   0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
